"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class pos_gps_t(object):
    __slots__ = ["robotid", "latitude", "longitude", "altitude"]

    def __init__(self):
        self.robotid = 0
        self.latitude = 0.0
        self.longitude = 0.0
        self.altitude = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(pos_gps_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">Bfff", self.robotid, self.latitude, self.longitude, self.altitude))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != pos_gps_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pos_gps_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = pos_gps_t()
        self.robotid, self.latitude, self.longitude, self.altitude = struct.unpack(">Bfff", buf.read(13))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if pos_gps_t in parents: return 0
        tmphash = (0xb2db8b1e5b0b6aa) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if pos_gps_t._packed_fingerprint is None:
            pos_gps_t._packed_fingerprint = struct.pack(">Q", pos_gps_t._get_hash_recursive([]))
        return pos_gps_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

